# Github uses redcarpet internally, we will use it here
markdown: redcarpet
redcarpet:
  extensions: ["smart"]
pygments: true
permalink: /posts/:title
title: Jekyll Uptrend Theme
# Note leave off trailing/
production_url : http://blogresideshere.com
description: Jeckyll Uptrend Theme
